module.exports = {
    es: {
        translation: {
            WELCOME_MSG: 'Bienvenido a recomendacion de series, para ver las funcionalidades de esta Alexa Skill pide me: "Ayuda"',
            LAUNCH_REQUEST_SERIE_GUADADA:'Hola tu ultima serie guardade fue ',
            headerTitleONE:'Por Actor',
            text_ONE_eleccion:"Para hacer una busqueda por actor por favor dime algo parecido a: 'Recomiendame una serie donde salga el actor kit harington'",
            headerTitleTWO:'Por categoria',
            text_TWO_eleccion:"Para hacer una busqueda por categoria por favor dime algo parecido a:'recomiendame una serie de la categoria drama'",
            headerTitleTRHEE:'Por año',
            text_TRHEE_eleccion:"Para hacer una busqueda por año por favor dime algo parecido a:'Recomiendame una serie del año 2016'",
            headerTitleFOR:'Por region',
            text_FOR_eleccion:"Para hacer una busqueda por region por favor dime algo parecido a:'Quiero una serie de la region de europa'",
            headerTitleFIVE:'Por plataforma',
            text_FIVE_eleccion:"Para hacer una busqueda por plataforma por favor dime algo parecido a:'Recomiendame una serie que sea de la plataforma de HBO'",
            descripcion_eleccion:"Para ver las opciones de recomendaciones de esta skill pide me \"Ayuda\"",
            eleccion_error:"No tenemos ese tipo de eleccion por favor ingresa las que se indican'",
            Guardar_serie: "Guarda esta serie diciendo:,  \"guardar para despues\"",
            recomendar: 'Claro te recomiendo la serie: ',
            recomendar_por_actor_error: 'No se encontraron series con ese actor principal, intenta con otro',
            recomendar_por_categoria_error: "No se encontraron series con esa categoria, intenta con otro",
            recomendar_por_anio_error: "No se encontraron series en ese año, intenta con otro",
            recomendar_por_Region_error: "No se encontraron series en esa region, intenta con otro",
            recomendar_por_plataforma_error: "No se encontraron series en esta plataforma, intenta con otro",
            confirmar_guardado_p1:'Claro guardare la serie',
            confirmar_guardado_p2:' para que la veas despues, di "mi serie guardada" para recordar que serie guardaste',
            descripcion_series_guardadas:"Para ver las opciones de recomendaciones de esta skill  pideme \"Ayuda\"",
            descripcion_series_guardadasP1:"La serie que guardaste para ver despues fue: ",
            descripcion_series_guardadasP2:' pide "Ayuda" para ver las opciones de recomendaciones de esta skill ',
            ayuda:'¿Tienes problemas con esta skill?, prueba diciendo alguna de las siguientes opciones por ejemplo "quiero buscar una serie por actor, categoria, año, region, categoria o plataforma"',
            cacelar_parar:'Hasta luego!, que vuelvas pronto, para volver a usarme di, "Recomiendar serie"',
            fallback:'Lo siento, no entiendo lo que quieres decirme, prueba de nuevo',
            welcome_one: "Bienvenido a recomendacion de series",
            welcome_help: "Para ver las opciones de esta Alexa skil, Pídeme : \"Ayuda\" ",
            help_title: "¿No sabes usar esta Skill?",
            help_subtitle : "Prueba diciendome alguna de las siguientes opciones: ",
            help_OpOne:"Por Categoria",
            help_OpTwo:"Por Año",
            help_OpThree: "Por Region",
            help_OpFor:"Por Actor",
            help_OpFive:"Por Plataforma",
            cancel_stop_one:"Hasta luego!, espero vuelvas pronto",
            cancel_stop_two:"Para volver a usarme di, \"recomendar serie\""
        }
    },
    en: {
        translation: {
            WELCOME_MSG: 'Welcome to series recommendation. To see the functionalities of this Alexa Skill, ask me: "Help"',
            LAUNCH_REQUEST_SERIE_GUADADA: 'Hello, your last saved series was ',
            headerTitleONE: 'By Actor',
            text_ONE_eleccion: "To search by actor, please tell me something like: 'Recommend me a series with actor Kit Harington'",
            headerTitleTWO: 'By Category',
            text_TWO_eleccion: "To search by category, please tell me something like: 'Recommend me a drama series'",
            headerTitleTRHEE: 'By Year',
            text_TRHEE_eleccion: "To search by year, please tell me something like: 'Recommend me a series from 2016'",
            headerTitleFOR: 'By Region',
            text_FOR_eleccion: "To search by region, please tell me something like: 'I want a series from the European region'",
            headerTitleFIVE: 'By Platform',
            text_FIVE_eleccion: "To search by platform, please tell me something like: 'Recommend me a series from HBO platform'",
            descripcion_eleccion: "To see the options for recommendations in this skill, ask me 'Help'",
            eleccion_error: "We don't have that type of selection. Please enter the indicated ones.",
            Guardar_serie: "Save this series by saying: 'Save for later'",
            recomendar: 'Sure, I recommend the series: ',
            recomendar_por_actor_error: 'No series found with that lead actor. Please try with another one.',
            recomendar_por_categoria_error: "No series found in that category. Please try with another one.",
            recomendar_por_anio_error: "No series found in that year. Please try with another one.",
            recomendar_por_Region_error: "No series found in that region. Please try with another one.",
            recomendar_por_plataforma_error: "No series found on this platform. Please try with another one.",
            confirmar_guardado_p1: 'Sure, I will save the series',
            confirmar_guardado_p2: ' for you to watch later, say "my saved series" to remember which series you saved',
            descripcion_series_guardadas: "To see the options for recommendations in this skill, ask me 'Help'",
            descripcion_series_guardadasP1: "The series you saved to watch later was: ",
            descripcion_series_guardadasP2: ' ask "Help" to see the options for recommendations in this skill',
            ayuda: 'Having trouble with this skill? Try saying one of the following options, for example, "I want to search for a series by actor, category, year, region, or platform"',
            cacelar_parar: 'Goodbye! Come back soon. To use me again, say "Recommend a series".',
            fallback: "I'm sorry, I don't understand what you're trying to tell me. Please try again.",
            welcome_one: "Welcome to series recommendation",
            welcome_help: "To see the options of this Alexa skill, ask me: \"Help\"",
            help_title: "Don't know how to use this skill?",
            help_subtitle: "Try saying one of the following options:",
            help_OpOne: "By Category",
            help_OpTwo: "By Year",
            help_OpThree: "By Region",
            help_OpFor: "By Actor",
            help_OpFive: "By Platform",
            cancel_stop_one: "Goodbye! Hope you come back soon.",
            cancel_stop_two: "To use me again, say \"Recommend a series\"."
        }
    }
}